/**
 * HomeBlend — Supabase client
 *
 * Schema mapping:
 *   "rooms"           → blends            (invite_code = join code, auto-generated by DB)
 *   "room members"    → blend_members     (+ profiles for display name / avatar)
 *   "room properties" → room_properties   (integer mock property IDs)
 *   "votes"           → room_votes        ("like" | "dislike", normalised to +1/-1 for the algorithm)
 *   "join requests"   → blend_join_requests
 *   "saved props"     → saved_properties
 */
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL     = import.meta.env.VITE_SUPABASE_URL      || "";
const SUPABASE_ANON    = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

export const supabase        = SUPABASE_URL && SUPABASE_ANON
  ? createClient(SUPABASE_URL, SUPABASE_ANON)
  : null;
export const isSupabaseReady = Boolean(SUPABASE_URL && SUPABASE_ANON);

const AVATAR_COLORS = ["#A67C3D","#5C8A6B","#7B6FA0","#C0624A","#4A7EA0","#8A6B5C"];
export function randomAvatarColor() {
  return AVATAR_COLORS[Math.floor(Math.random() * AVATAR_COLORS.length)];
}

// ── Internal helpers ──────────────────────────────────────────────────────────
function guard() {
  if (!supabase) throw new Error("Supabase not configured — add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local");
}

export function isSchemaMissing(err) {
  if (!err) return false;
  const msg = (err?.message || err?.details || err?.hint || "").toLowerCase();
  return msg.includes("does not exist") || msg.includes("schema cache") ||
    msg.includes("relation") || err?.code === "PGRST200" || err?.code === "42P01" || err?.code === "PGRST205";
}

// Wraps a fn(); returns `fallback` instead of throwing on missing-table errors.
async function safe(fn, fallback) {
  try {
    return await fn();
  } catch (err) {
    if (isSchemaMissing(err)) {
      console.warn("[HomeBlend] table missing — run migration 005:", err.message);
      return fallback;
    }
    throw err;
  }
}

// Throws only if err is not a "duplicate / already exists" error.
function ignoreDuplicate(err) {
  if (!err) return;
  const msg = (err.message || "").toLowerCase();
  if (msg.includes("duplicate") || msg.includes("unique") || err.code === "23505") return;
  throw err;
}

// ── Auth ──────────────────────────────────────────────────────────────────────
export async function signUp(email, password, displayName) {
  guard();
  const { data, error } = await supabase.auth.signUp({ email, password,
    options: { data: { display_name: displayName || email.split("@")[0] } },
  });
  if (error) throw error;
  // Create profile in JS — no trigger required
  if (data.user) {
    await safe(() => supabase.from("profiles").insert({
      id: data.user.id,
      display_name: displayName || email.split("@")[0],
      avatar_color: randomAvatarColor(),
    }), null);
  }
  return data;
}

export async function signIn(email, password) {
  guard();
  const { data, error } = await supabase.auth.signInWithPassword({ email, password });
  if (error) throw error;
  return data;
}

export async function signOut() { await supabase?.auth.signOut(); }

// ── Profiles ──────────────────────────────────────────────────────────────────
export async function fetchProfile(userId) {
  guard();
  return safe(async () => {
    const { data } = await supabase.from("profiles").select("*").eq("id", userId).maybeSingle();
    return data;
  }, null);
}

export async function ensureProfile(userId, displayName) {
  guard();
  const fallback = { id: userId, display_name: displayName || "User", avatar_color: randomAvatarColor() };
  return safe(async () => {
    // Try to fetch first
    const { data: existing } = await supabase.from("profiles").select("*").eq("id", userId).maybeSingle();
    if (existing) return existing;
    // Not found — insert
    const { data, error } = await supabase.from("profiles")
      .insert({ id: userId, display_name: displayName || "User", avatar_color: randomAvatarColor() })
      .select().maybeSingle();
    if (error) { ignoreDuplicate(error); return fallback; }
    return data || fallback;
  }, fallback);
}

export async function updateProfile(userId, updates) {
  guard();
  return safe(async () => {
    const { data, error } = await supabase.from("profiles")
      .update(updates).eq("id", userId).select().maybeSingle();
    if (error) throw error;
    return data;
  }, null);
}

// ── Saved Properties ──────────────────────────────────────────────────────────
export async function fetchSavedPropertyIds(userId) {
  guard();
  return safe(async () => {
    const { data } = await supabase.from("saved_properties").select("property_id").eq("user_id", userId);
    return (data || []).map(r => r.property_id);
  }, []);
}

export async function saveProperty(userId, propertyId) {
  guard();
  return safe(() =>
    supabase.from("saved_properties")
      .insert({ user_id: userId, property_id: propertyId })
      .then(({ error }) => { ignoreDuplicate(error); }),
    null);
}

export async function unsaveProperty(userId, propertyId) {
  guard();
  return safe(() =>
    supabase.from("saved_properties").delete().eq("user_id", userId).eq("property_id", propertyId),
    null);
}

// ── Rooms (blends) ────────────────────────────────────────────────────────────
// The join code is blends.invite_code — an 8-char string auto-generated by the DB.

export async function createRoom(name, userId) {
  guard();
  // Direct insert — no RPC needed
  const { data, error } = await supabase.from("blends")
    .insert({ name: name || "My Room", created_by: userId })
    .select().maybeSingle();
  if (error) {
    if (isSchemaMissing(error)) throw new Error("Database tables not set up. Run migration 005_homeblend_addon_tables.sql in your Supabase SQL editor.");
    throw error;
  }
  // Auto-join creator as owner (check first — blend_members has no unique constraint)
  const { data: existing } = await supabase.from("blend_members")
    .select("id").eq("blend_id", data.id).eq("user_id", userId).maybeSingle();
  if (!existing) {
    await supabase.from("blend_members")
      .insert({ blend_id: data.id, user_id: userId, role: "owner" });
  }
  // Persist display name
  await _upsertProfile(userId);
  return { ...data, room_code: data.invite_code };
}

export async function fetchRoom(inviteCode) {
  guard();
  return safe(async () => {
    const { data } = await supabase.from("blends")
      .select("*").eq("invite_code", inviteCode.toUpperCase()).maybeSingle();
    return data ? { ...data, room_code: data.invite_code } : null;
  }, null);
}

export async function fetchUserRooms(userId) {
  guard();
  return safe(async () => {
    const { data, error } = await supabase.from("blend_members")
      .select("joined_at, blends(id, name, invite_code, created_by, created_at)")
      .eq("user_id", userId)
      .order("joined_at", { ascending: false });
    if (error) throw error;
    return (data || []).map(r => r.blends).filter(Boolean).map(b => ({ ...b, room_code: b.invite_code }));
  }, []);
}

export async function joinRoom(blendId, userId, displayName, avatarColor) {
  guard();
  return safe(async () => {
    // Check before insert (blend_members has no unique constraint)
    const { data: existing } = await supabase.from("blend_members")
      .select("id").eq("blend_id", blendId).eq("user_id", userId).maybeSingle();
    if (!existing) {
      const { error } = await supabase.from("blend_members")
        .insert({ blend_id: blendId, user_id: userId, role: "member" });
      if (error) ignoreDuplicate(error);
    }
    // Best-effort profile save
    await _upsertProfile(userId, displayName, avatarColor);
  }, undefined);
}

export async function leaveRoom(blendId, userId) {
  guard();
  return safe(() =>
    supabase.from("blend_members").delete().eq("blend_id", blendId).eq("user_id", userId),
    null);
}

export async function fetchMembers(blendId) {
  guard();
  return safe(async () => {
    const { data: members, error } = await supabase.from("blend_members")
      .select("id, blend_id, user_id, role, joined_at")
      .eq("blend_id", blendId).order("joined_at");
    if (error) throw error;
    if (!members?.length) return [];

    // Fetch profiles separately (no FK join between blend_members and profiles)
    const userIds = members.map(m => m.user_id);
    let profileMap = {};
    try {
      const { data: profs } = await supabase.from("profiles")
        .select("id, display_name, avatar_color").in("id", userIds);
      (profs || []).forEach(p => { profileMap[p.id] = p; });
    } catch { /* profiles table not yet created — use defaults */ }

    return members.map(m => ({
      ...m,
      auth_user_id: m.user_id,
      display_name: profileMap[m.user_id]?.display_name || "Member",
      avatar_color: profileMap[m.user_id]?.avatar_color || "#A67C3D",
    }));
  }, []);
}

// ── Room Properties ───────────────────────────────────────────────────────────
export async function addPropertyToRoom(blendId, propertyId, userId) {
  guard();
  // Use upsert so duplicate rows are silently ignored (no separate SELECT needed)
  const { error } = await supabase.from("room_properties").upsert(
    { blend_id: blendId, property_id: Number(propertyId), added_by: userId },
    { onConflict: "blend_id,property_id" }
  );
  if (error) {
    // 23505 = unique violation (already exists) — safe to ignore
    if (error.code === "23505") return;
    console.error("[HomeBlend] addPropertyToRoom failed:", error);
    throw error;
  }
}

export async function removePropertyFromRoom(blendId, propertyId) {
  guard();
  return safe(() =>
    supabase.from("room_properties").delete().eq("blend_id", blendId).eq("property_id", propertyId),
    null);
}

export async function fetchRoomProperties(blendId) {
  guard();
  return safe(async () => {
    const { data, error } = await supabase.from("room_properties")
      .select("*").eq("blend_id", blendId).order("added_at");
    if (error) throw error;
    // Ensure property_id is always a JS number (not string) so includes() works
    return (data || []).map(r => ({ ...r, property_id: Number(r.property_id), room_id: blendId }));
  }, []);
}

// ── Votes ─────────────────────────────────────────────────────────────────────
// Stored as "like"/"dislike"; normalised to +1/-1 when fetched so the blend
// algorithm and all UI components work without changes.

export async function recordVote(blendId, userId, propertyId, vote) {
  guard();
  const pid = Number(propertyId);
  if (vote === null) {
    await supabase.from("room_votes").delete()
      .eq("blend_id", blendId).eq("user_id", userId).eq("property_id", pid);
    return;
  }
  const voteText = (vote === 1 || vote === "like") ? "like" : "dislike";
  const { error } = await supabase.from("room_votes").upsert(
    { blend_id: blendId, user_id: userId, property_id: pid, vote: voteText },
    { onConflict: "blend_id,user_id,property_id" }
  );
  if (error) {
    console.error("[HomeBlend] recordVote failed:", error);
    throw error;
  }
}

export async function fetchVotes(blendId) {
  guard();
  return safe(async () => {
    const { data } = await supabase.from("room_votes").select("*").eq("blend_id", blendId);
    return (data || []).map(v => ({
      ...v,
      room_id:  blendId,
      vote:     v.vote === "like" ? 1 : -1,
      voteText: v.vote,
    }));
  }, []);
}

// ── Join Requests ─────────────────────────────────────────────────────────────
export async function fetchJoinRequests(blendId) {
  guard();
  return safe(async () => {
    const { data, error } = await supabase.from("blend_join_requests")
      .select("*").eq("blend_id", blendId).order("created_at", { ascending: false });
    if (error) throw error;
    return (data || []).map(r => ({ ...r, display_name: r.email?.split("@")[0] || "User" }));
  }, []);
}

export async function requestToJoin(blendId, userId, displayName) {
  guard();
  return safe(async () => {
    const { data: user } = await supabase.auth.getUser();
    const email = user?.user?.email || "";
    // Check existing request
    const { data: existing } = await supabase.from("blend_join_requests")
      .select("id, status").eq("blend_id", blendId).eq("user_id", userId).maybeSingle();
    if (existing) {
      if (existing.status === "declined") {
        await supabase.from("blend_join_requests").update({ status: "pending" }).eq("id", existing.id);
      }
      return existing.status;
    }
    await supabase.from("blend_join_requests")
      .insert({ blend_id: blendId, user_id: userId, email, status: "pending" });
    return "pending";
  }, "pending");
}

export async function respondToJoinRequest(requestId, accept) {
  guard();
  return safe(async () => {
    const status = accept ? "accepted" : "declined";
    await supabase.from("blend_join_requests").update({ status }).eq("id", requestId);
    if (accept) {
      const { data: req } = await supabase.from("blend_join_requests")
        .select("blend_id, user_id").eq("id", requestId).maybeSingle();
      if (req) {
        const { data: existing } = await supabase.from("blend_members")
          .select("id").eq("blend_id", req.blend_id).eq("user_id", req.user_id).maybeSingle();
        if (!existing) {
          await supabase.from("blend_members")
            .insert({ blend_id: req.blend_id, user_id: req.user_id, role: "member" });
        }
      }
    }
    return status;
  }, accept ? "accepted" : "declined");
}

// ── Realtime ──────────────────────────────────────────────────────────────────
export function subscribeToRoom(blendId, { onVotes, onProperties, onMembers } = {}) {
  if (!supabase) return null;
  const channel = supabase.channel(`blend:${blendId}`);
  if (onVotes) channel.on("postgres_changes",
    { event: "*", schema: "public", table: "room_votes", filter: `blend_id=eq.${blendId}` }, onVotes);
  if (onProperties) channel.on("postgres_changes",
    { event: "*", schema: "public", table: "room_properties", filter: `blend_id=eq.${blendId}` }, onProperties);
  if (onMembers) channel.on("postgres_changes",
    { event: "*", schema: "public", table: "blend_members", filter: `blend_id=eq.${blendId}` }, onMembers);
  channel.subscribe();
  return channel;
}

export function unsubscribeFromRoom(channel) {
  if (channel && supabase) supabase.removeChannel(channel);
}

// ── Internal ──────────────────────────────────────────────────────────────────
async function _upsertProfile(userId, displayName, avatarColor) {
  if (!userId) return;
  try {
    const { data: existing } = await supabase.from("profiles").select("id").eq("id", userId).maybeSingle();
    if (existing) {
      if (displayName) await supabase.from("profiles").update({ display_name: displayName }).eq("id", userId);
    } else {
      await supabase.from("profiles").insert({
        id: userId, display_name: displayName || "User", avatar_color: avatarColor || randomAvatarColor(),
      });
    }
  } catch { /* profiles table not created yet */ }
}
